apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-python-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-python-app
  template:
    metadata:
      labels:
        app: harness-python-app
    spec:
      containers:
      - name: app
        image: pavandath510/harness-py-app:latest
        ports:
        - containerPort: 8080
        # NO crash command! App runs normally
        # But might have performance issues
        
        # Add health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        # Optional: Add tight resources to stress app
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: harness-python-app-service
  namespace: default
spec:
  selector:
    app: harness-python-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
