apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-python-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-python-app
  template:
    metadata:
      labels:
        app: harness-python-app
    spec:
      containers:
      - name: app
        image: pavandath510/harness-py-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: harness-python-app-service
  namespace: default
spec:
  selector:
    app: harness-python-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # Optional, remove if you want random port
  type: NodePort
